export const APP_ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  resetPassword: "/reset-password",
  completeProfile: "/complete-profile",
  uiKit: "/ui-kit",
  profile: "/profile",
  shipments: "/shipments",
  newShipment: "/shipments/new",
  shipmentDetail: "/shipments/:id",
  track: "/track",
  parcelTemplates: "/parcel-templates",
  newParcelTemplate: "/parcel-templates/new",
  editParcelTemplate: "/parcel-templates/:id/edit",
} as const;
